### ISSUE TITLE
I made a similar extension using Do Not Merge WIP as a starting point

### ISSUE THREAD

**Issue by rafaeleyng** [sanemat/do-not-merge-wip-for-github#324]
Hello there 🙂 

This is not really an issue or a question, I just wanted to let you know that I recently made an extension called [No Merge Today](https://github.com/rafaeleyng/no-merge-today). I used Do Not Merge WIP as a starting point since I've never built a Chrome extension before. So, thank you for that!

I also was able to solve a couple of scenarios that Do Not Merge WIP does not handle. Most notably the case where you reach the pull request page by client-side navigation, instead of a full-page reload (Do Not Merge WIP won't trigger in this case, No Merge Today will). A simple way of testing this scenario is to, having Do Not Merge WIP enabled, navigate to https://github.com/rafaeleyng/no-merge-today/pulls and then click on the PR 2 there. It shouldn't trigger the content script that blocks the button. But after a reload while being on the PR page, it triggers.

I also used mutation observer to react more quickly to DOM changes (instead of relying on a setInterval), and message passing to react immediately to configuration changes in the action popup.

I hope this can be useful 👋

**Comment by sanemat** [comment]
Thank you for your sharing! I'm glad to hear that :smile_cat:
