### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bfontaine** [sanemat/do-not-merge-wip-for-github#54]
Hello,

Would you mind adding a license to your project? Thanks!

**Comment by sanemat** [comment]
@bfontaine thanks,

I want to change (add) License to MIT license.

## Pros

The license becomes clear

## Cons

Nothing

Do you find any problems? @takkanm  @fukayatsu

**Comment by sanemat** [comment]
cc/ @dtaniwaki @sakatam

**Comment by dtaniwaki** [comment]
:+1:

**Comment by sakatam** [comment]
no prob!

**Comment by takkanm** [comment]
@sanemat :+1:

**Comment by fukayatsu** [comment]
:+1:

**Comment by sanemat** [comment]
Thanks!
